http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
add.interactive.usebuiltin=true
core.autocrlf=true
core.fscache=true
core.symlinks=true
core.editor="D:\\Microsoft VS Code\\bin\\code" --wait
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
winupdater.recentlyseenversion=2.25.0.windows.1
user.email=markuzemb18@gmail.com
user.name=Marcos Eduardo
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.autocrlf=true
core.excludesfile=C:\Users\Marcos\Documents\gitignore_global.txt
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://github.com/Markuz25/YAML.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
